name: incar_passenger
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  google_maps_flutter: ^2.5.0
  firebase_auth: ^6.0.2
  google_fonts: ^6.1.0
  permission_handler: ^12.0.1
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
